#!/usr/bin/env python3
"""Compile the vendor-agnostic agent harness into per-vendor configs.

The single source of truth lives in .agents/ (permissions.toml, hooks.toml,
skills/). This script translates that intent into each vendor's native layout:

  Claude Code -> .claude/settings.json   (permissions passthrough + hooks)
  Codex       -> .codex/config.toml       (filesystem deny + network + hooks)
                 .codex/rules/default.rules (Starlark prefix_rule)

Skills are mirrored verbatim (one dir per skill) from .agents/skills/ into each
vendor's .<vendor>/skills/. A root CLAUDE.md shim (`@AGENTS.md`) is generated so
Claude Code — which doesn't read AGENTS.md natively — picks up the shared file.

All generated mirrors are gitignored and read-only: edit .agents/, never them.
A SessionStart hook reruns this on every session, so mirrors stay fresh; output
is silent when nothing changed. Manual check: `python3 .agents/setup.py --check`.

Adding a vendor: write a compile function that returns the file's text, register
its output in `_file_targets()`, and add its short name to `SKILL_VENDORS` if it
consumes skills. See docs/adding-a-vendor.md for the full recipe.

Requires Python 3.11+ (stdlib tomllib). No external dependencies.
"""

import json
import re
import shutil
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
AGENTS_DIR = REPO_ROOT / ".agents"
MARKER = "GENERATED by .agents/setup.py — do not edit by hand"
ENTRY_RE = re.compile(r"^([A-Za-z]+)(?:\((.*)\))?$")

# Vendors that consume skills (one dir per skill mirrored into .<vendor>/skills/).
SKILL_VENDORS = ("claude", "codex")
# Codex groups permissions under a named profile; this is its label.
PROFILE = "project"
CLAUDE_MD_CONTENT = "@AGENTS.md\n"


def load_source() -> dict:
    return {
        "permissions": tomllib.loads((AGENTS_DIR / "permissions.toml").read_text()),
        "hooks": tomllib.loads((AGENTS_DIR / "hooks.toml").read_text()),
    }


def _parse_entry(s: str) -> tuple[str, str | None]:
    """Split a `Tool` or `Tool(pattern)` entry into (tool, pattern|None)."""
    m = ENTRY_RE.match(s)
    return (m.group(1), m.group(2)) if m else (s, None)


# ---------------------------------------------------------------- Claude Code
CLAUDE_FILE_EXTRACT = "$(jq -r '.tool_input.file_path // empty')"


def _render_claude_hook(cmd: str) -> str | None:
    """Substitute hook placeholders for Claude. Skip what we can't map exactly."""
    if "{repo_root}" in cmd:
        return None  # no verified Claude mapping; skip rather than guess
    return cmd.replace("{file}", CLAUDE_FILE_EXTRACT)


def compile_claude(src: dict) -> str:
    perms, hooks = src["permissions"], src["hooks"]
    post_edit = []
    for h in hooks.get("post_edit", []):
        cmd = _render_claude_hook(h["run"])
        if cmd is not None:
            post_edit.append({"matcher": "Edit|Write|MultiEdit",
                              "hooks": [{"type": "command", "command": cmd}]})
    session_start = []
    for h in hooks.get("session_start", []):
        cmd = _render_claude_hook(h["run"])
        if cmd is not None:
            session_start.append({"hooks": [{"type": "command", "command": cmd}]})
    settings = {
        "_generated": MARKER,
        "permissions": {k: list(perms.get(k, [])) for k in ("allow", "ask", "deny")},
        "hooks": {"PostToolUse": post_edit, "SessionStart": session_start},
    }
    return json.dumps(settings, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------- Codex
def _bash_to_prefix(pattern: str) -> list[str] | None:
    """Turn a Bash(...) glob into a Codex prefix_rule token list, or None if the
    pattern can't be expressed as a leading-token prefix (so we skip it)."""
    parts = pattern.strip().split()
    if not parts:
        return None
    out: list[str] = []
    for p in parts:
        if p == "*":
            return out if out else None
        if "*" in p:
            if not p.endswith("*"):
                return None
            stripped = p[:-1]
            if not stripped or "*" in stripped:
                return out if out else None
            if stripped.startswith(("/", "~", ".")):
                return None
            out.append(stripped)
            return out
        out.append(p)
    return out if out else None


def _fs_deny_paths(deny_entries: list[str]) -> list[str]:
    """Pull filesystem paths (e.g. .env*) out of deny entries for Codex's
    path-based deny list."""
    paths: set[str] = set()
    for entry in deny_entries:
        tool, arg = _parse_entry(entry)
        if not arg:
            continue
        if tool == "Read":
            paths.add(arg[2:] if arg.startswith("./") else arg)
        elif tool == "Bash":
            for tok in arg.split():
                if ".env" in tok:
                    paths.add(tok[2:] if tok.startswith("./") else tok)
    return sorted(paths)


def _toml_basic_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def compile_codex_config(perms: dict, hooks: dict) -> str:
    deny_paths = _fs_deny_paths(perms.get("deny", []))
    has_web = any(_parse_entry(e)[0] in ("WebSearch", "WebFetch") for e in perms.get("allow", []))
    lines = [
        f"# {MARKER}", "#",
        "# Permissions intent from .agents/permissions.toml, enforced via:",
        f"#   - filesystem deny under [permissions.{PROFILE}.filesystem]",
        "#   - Starlark prefix rules in .codex/rules/default.rules", "",
        'approval_policy = "on-request"', 'sandbox_mode = "workspace-write"',
        f'default_permissions = "{PROFILE}"', "",
        f"[permissions.{PROFILE}]", f'description = "{PROFILE} dev profile"',
        'extends = ":workspace"',
    ]
    if deny_paths:
        lines += ["", f"[permissions.{PROFILE}.filesystem]"]
        lines += [f'":workspace_roots"."{p}" = "deny"' for p in deny_paths]
    if has_web:
        lines += ["", f"[permissions.{PROFILE}.network]", "enabled = true", 'mode = "full"']
    for h in hooks.get("session_start", []):
        cmd = h["run"]
        if "{file}" in cmd or "{repo_root}" in cmd:
            continue
        lines += ["", "[[hooks.SessionStart]]", "", "[[hooks.SessionStart.hooks]]",
                  'type = "command"', f"command = {_toml_basic_string(cmd)}"]
    return "\n".join(lines) + "\n"


def compile_codex_rules(perms: dict) -> str:
    decision_for = {"ask": "prompt", "deny": "forbidden"}
    lines = [
        f"# {MARKER}", "#",
        "# Starlark prefix rules from .agents/permissions.toml.",
        "# `allow` is Codex's default and is not materialized here.",
        "# Filesystem-path patterns (.env*) are enforced in config.toml.", "",
    ]
    skipped: list[str] = []
    for verdict in ("ask", "deny"):
        for entry in perms.get(verdict, []):
            tool, arg = _parse_entry(entry)
            if tool != "Bash" or arg is None:
                continue
            if any(".env" in tok for tok in arg.split()):
                continue
            prefix = _bash_to_prefix(arg)
            if prefix is None:
                skipped.append(entry)
                continue
            pattern = "[" + ", ".join(f'"{p}"' for p in prefix) + "]"
            lines += ["prefix_rule(", f"    pattern={pattern},",
                      f'    decision="{decision_for[verdict]}",', ")", ""]
    if skipped:
        lines.append("# Skipped (not expressible as prefix_rule):")
        lines += [f"#   {s}" for s in skipped]
        lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------- skills + shim
def _dir_files(root: Path) -> dict[Path, Path]:
    if not root.exists():
        return {}
    return {p.relative_to(root): p for p in root.rglob("*") if p.is_file()}


def _skill_sources() -> dict[str, Path]:
    src_dir = AGENTS_DIR / "skills"
    sources: dict[str, Path] = {}
    for s in sorted(src_dir.glob("*/SKILL.md")) if src_dir.exists() else []:
        sources[s.parent.name] = s
    return sources


def mirror_skills() -> None:
    sources = _skill_sources()
    for vendor in SKILL_VENDORS:
        vendor_dir = REPO_ROOT / f".{vendor}" / "skills"
        if vendor_dir.exists():
            for entry in vendor_dir.iterdir():
                if entry.is_dir() and entry.name not in sources and (entry / "SKILL.md").exists():
                    shutil.rmtree(entry)
                    print(f"removed orphan skill: {entry.relative_to(REPO_ROOT)}")
        for name, skill_md in sorted(sources.items()):
            src_files = _dir_files(skill_md.parent)
            dest_dir = vendor_dir / name
            dest_files = _dir_files(dest_dir)
            for rel in sorted(dest_files.keys() - src_files.keys(), reverse=True):
                (dest_dir / rel).unlink()
            for rel, src in sorted(src_files.items()):
                dest = dest_dir / rel
                content = src.read_bytes()
                if dest.exists() and dest.read_bytes() == content:
                    continue
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(content)
                print(f"mirrored {dest.relative_to(REPO_ROOT)}")


def mirror_root_claude_md() -> None:
    """Root CLAUDE.md shim so Claude Code inlines the shared AGENTS.md."""
    path = REPO_ROOT / "CLAUDE.md"
    if not (REPO_ROOT / "AGENTS.md").exists():
        return
    if path.exists() and path.read_text() == CLAUDE_MD_CONTENT:
        return
    path.write_text(CLAUDE_MD_CONTENT)
    print("wrote CLAUDE.md")


# ---------------------------------------------------------------- I/O
def write_if_safe(path: Path, content: str, force: bool) -> None:
    if path.exists():
        existing = path.read_text()
        if existing == content:
            return
        if not force and MARKER not in existing:
            print(f"refusing to overwrite hand-edited file: {path}", file=sys.stderr)
            print("use --force to overwrite", file=sys.stderr)
            sys.exit(1)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"wrote {path.relative_to(REPO_ROOT)}")


def _file_targets(src: dict) -> list[tuple[Path, str]]:
    """The full set of (path, generated-content) the compiler owns.

    To add a vendor, append its outputs here (and add its name to SKILL_VENDORS
    if it consumes skills). Everything downstream — writing, --check staleness,
    overwrite protection — picks it up automatically.
    """
    perms, hooks = src["permissions"], src["hooks"]
    return [
        (REPO_ROOT / ".claude" / "settings.json", compile_claude(src)),
        (REPO_ROOT / ".codex" / "config.toml", compile_codex_config(perms, hooks)),
        (REPO_ROOT / ".codex" / "rules" / "default.rules", compile_codex_rules(perms)),
    ]


def _collect_stale(targets: list[tuple[Path, str]]) -> list[Path]:
    stale: list[Path] = []
    for path, content in targets:
        if not path.exists() or path.read_text() != content:
            stale.append(path.relative_to(REPO_ROOT))
    sources = _skill_sources()
    for vendor in SKILL_VENDORS:
        vendor_dir = REPO_ROOT / f".{vendor}" / "skills"
        if vendor_dir.exists():
            for entry in vendor_dir.iterdir():
                if entry.is_dir() and entry.name not in sources and (entry / "SKILL.md").exists():
                    stale.append(entry.relative_to(REPO_ROOT))
        for name, skill_md in sources.items():
            src_files = _dir_files(skill_md.parent)
            dest_dir = vendor_dir / name
            for rel in _dir_files(dest_dir).keys() - src_files.keys():
                stale.append((dest_dir / rel).relative_to(REPO_ROOT))
            for rel, src in src_files.items():
                dest = dest_dir / rel
                if not dest.exists() or dest.read_bytes() != src.read_bytes():
                    stale.append(dest.relative_to(REPO_ROOT))
    cm = REPO_ROOT / "CLAUDE.md"
    if (REPO_ROOT / "AGENTS.md").exists() and (not cm.exists() or cm.read_text() != CLAUDE_MD_CONTENT):
        stale.append(Path("CLAUDE.md"))
    return stale


def main() -> None:
    force = "--force" in sys.argv
    src = load_source()
    targets = _file_targets(src)
    if "--check" in sys.argv:
        stale = _collect_stale(targets)
        if stale:
            print("stale mirrors:", file=sys.stderr)
            for p in stale:
                print(f"  {p}", file=sys.stderr)
            print("run: python3 .agents/setup.py", file=sys.stderr)
            sys.exit(1)
        print("mirrors consistent")
        return
    for path, content in targets:
        write_if_safe(path, content, force)
    mirror_skills()
    mirror_root_claude_md()


if __name__ == "__main__":
    main()
